apiVersion: v1
kind: Secret
metadata:
  name: timer-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: <path:kv/data/tsungmn-timer-secret#db-url | base64encode>
  SPRING_DATASOURCE_USERNAME: <path:kv/data/tsungmn-timer-secret#db-username | base64encode>
  SPRING_DATASOURCE_PASSWORD: <path:kv/data/tsungmn-timer-secret#db-password | base64encode>
