apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timer-prod
resources:
  - ../../../base/fe

patches:
  - path: domain.json
    target:
      kind: Ingress
      name: fe-ingress
images:
  - name: tsungmnli/timer-fe
    newTag: 742761d9ee337b2b3a5d07c49b6e672d661a6261
