apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timer-fe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: timer.tsungmn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: timer-fe
                port:
                  number: 80
